# Generated by Django 4.2 on 2023-04-28 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('description', models.CharField(max_length=300)),
                ('h1', models.CharField(max_length=50)),
                ('mini_content', models.TextField()),
                ('price', models.IntegerField()),
                ('pup_date', models.DateField()),
                ('h2', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.categoryproduct')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.tag')),
            ],
        ),
    ]
