# Generated by Django 4.2 on 2023-05-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='icon',
            field=models.ImageField(blank=True, upload_to='uploads_icon'),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='slug',
            field=models.SlugField(),
        ),
    ]
